name: ai-rack

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:v0.9.5
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "3000:8080"
    environment:
      OPENAI_API_BASE_URL: http://litellm:4000/v1
      OPENAI_API_KEY: ${LITELLM_MASTER_KEY:-sk-1234}
      ENABLE_OLLAMA_API: false
      ENABLE_FORWARD_USER_INFO_HEADERS: true
      DATABASE_TYPE: postgresql
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: owui
      DATABASE_USER: owui_user
      DATABASE_PASSWORD: ${OWUI_DB_PASS:-owui_pass}
      DEFAULT_MODEL_PARAMS: |
        { "function_calling" : "native" }
      ENABLE_WEB_SEARCH: true
      WEB_SEARCH_ENGINE: duckduckgo
      DDGS_BACKEND: google
    volumes:
      - openwebui_data:/app/backend/data
    depends_on:
      litellm:
        condition: service_started
      postgres:
        condition: service_healthy

  litellm:
    image: ghcr.io/berriai/litellm:1.84.0-rc.1
    container_name: litellm
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://litellm_user:${LITELLM_DB_PASS:-litellm_pass}@postgres:5432/litellm
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY:-sk-1234}
      LITELLM_SALT_KEY: ${LITELLM_SALT_KEY:-sk-salt-1234}
      STORE_MODEL_IN_DB: "True"
    command: [ "--config", "/app/config.yaml" ]

    configs:
      - source: litellm_config
        target: /app/config.yaml
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASS:-postgres}
    ports:
      - "4432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U litellm_user -d litellm" ]
      interval: 10s
      timeout: 5s
      retries: 5
    configs:
      - source: pg_init_databases
        target: /docker-entrypoint-initdb.d/init-databases.sql

volumes:
  postgres_data:
  openwebui_data:

configs:
  litellm_config:
    content: |
      general_settings:
        store_prompts_in_spend_logs: true
        user_header_mappings:
          - header_name: 'X-OpenWebUI-User-Id'
            litellm_user_role: internal_user
          - header_name: 'X-OpenWebUI-User-Email'
            litellm_user_role: customer

      litellm_settings:
        default_internal_user_params:
          max_budget: 10.0
          budget_duration: weekly
        set_verbose: true
        extra_spend_tag_headers:
          - "X-OpenWebUI-User-Id"
          - "X-OpenWebUI-User-Email"

  pg_init_databases:
    content: |
      CREATE USER owui_user WITH PASSWORD '${OWUI_DB_PASS:-owui_pass}';
      CREATE USER litellm_user WITH PASSWORD '${LITELLM_DB_PASS:-litellm_pass}';

      CREATE DATABASE owui OWNER owui_user;
      CREATE DATABASE litellm OWNER litellm_user;
